root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./src"
  
  bin = "tmp/main"
  
  include_ext = ["go", "tpl", "tmpl", "html"]

  exlude_dir = ["kassets", "tmp", "vendor"]

[log]

  time = true

[run]
  cmd = "tmp/main"
