services:
  web:
    build: ./Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    working_dir: /app/src
    command: air
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=thready
      - DB_PASSWORD=secret
      - DB_NAME=thready

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=thready
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=thready
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
