AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Fargate service with Secrets Manager integration for Thready

Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  TargetGroupArn:
    Type: String
  ContainerImage:
    Type: String
    Description: ECR Image URI
  SecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret (e.g., contains DATABASE_URL)
  ALBSecurityGroupId:
    Type: String
    Description: Security Group for the ALB

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: thready-cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: thready-task-execution-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

  ECSTaskSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ALB to access ECS task
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroupId

  ThreadyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: thready-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: thready-app
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 8080
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Ref SecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/thready-app
              awslogs-region: ap-northeast-1
              awslogs-stream-prefix: ecs

  ThreadyService:
    Type: AWS::ECS::Service
    DependsOn:
      - ThreadyTaskDefinition
      - ECSTaskSecurityGroup
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ThreadyTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
          SecurityGroups:
            - !Ref ECSTaskSecurityGroup
      LoadBalancers:
        - ContainerName: thready-app
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroupArn

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster

  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !Ref ThreadyTaskDefinition

  ECSServiceName:
    Description: ECS Service Name
    Value: !Ref ThreadyService
