AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL for Thready

Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  DBUsername:
    Type: String
    NoEcho: true
  DBPassword:
    Type: String
    NoEcho: true

Resources:
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow PostgreSQL from ECS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS
      SubnetIds:
        - !Ref Subnet1
        - !Ref Subnet2

  ThreadyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      EngineVersion: 15.13
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      DBName: thready
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RdsSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: true
      MultiAZ: false
      BackupRetentionPeriod: 0

Outputs:
  DBEndpoint:
    Description: Endpoint of the RDS DB
    Value: !GetAtt ThreadyDB.Endpoint.Address
  RdsSecurityGroupId:
    Description: Security Group ID for ECS task access
    Value: !Ref RdsSecurityGroup
